# Generated by Django 5.1.7 on 2025-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0003_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
